# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2014-08-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cronologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_crono', models.IntegerField(blank=True, null=True)),
                ('fech_des', models.CharField(max_length=40)),
                ('fech_has', models.CharField(max_length=40)),
                ('carg_ante', models.CharField(max_length=40)),
                ('institucion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Descan_Trimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_des_tri', models.IntegerField(blank=True, null=True)),
                ('fech_solici', models.DateField(blank=True, null=True)),
                ('fech_fin', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('opci', models.CharField(choices=[('SOLICITUD DE PERMISO ', 'SOLICITUD DE PERMISO '), ('NOTIFICACIÓN DE INASISTENCIA ', 'NOTIFICACIÓN DE INASISTENCIA ')], max_length=50)),
                ('carg_libr_nom', models.CharField(blank=True, max_length=50, null=True)),
                ('enfer', models.CharField(blank=True, max_length=50, null=True)),
                ('accid', models.CharField(blank=True, max_length=50, null=True)),
                ('falle_fami_metro', models.CharField(blank=True, max_length=50, null=True)),
                ('falle_fami_exte', models.CharField(blank=True, max_length=50, null=True)),
                ('nacim_hij', models.CharField(blank=True, max_length=50, null=True)),
                ('com_ant_tribu', models.CharField(blank=True, max_length=50, null=True)),
                ('matrim', models.CharField(blank=True, max_length=50, null=True)),
                ('pre_natal', models.CharField(blank=True, max_length=50, null=True)),
                ('post_natal', models.CharField(blank=True, max_length=50, null=True)),
                ('asis_curs_confe', models.CharField(blank=True, max_length=50, null=True)),
                ('enfer_fami', models.CharField(blank=True, max_length=50, null=True)),
                ('estu_acade', models.CharField(blank=True, max_length=50, null=True)),
                ('dili_pers', models.CharField(blank=True, max_length=50, null=True)),
                ('otro', models.CharField(blank=True, max_length=150, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_evalua', models.IntegerField(blank=True, null=True)),
                ('periodo', models.CharField(max_length=40)),
                ('año', models.CharField(max_length=40)),
                ('escala', models.CharField(max_length=40)),
                ('nota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jubilacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Procesando', 'Procesando'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=50, null=True)),
                ('fecha_s', models.DateTimeField(auto_now_add=True)),
                ('cod_jubila', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('estatus', models.BooleanField(default=False)),
                ('adelanto', models.BooleanField()),
                ('dias', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Segu_Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_seg_soc', models.IntegerField(blank=True, null=True)),
                ('trami_pens', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20)),
                ('esta_seg_soc', models.CharField(choices=[('Egreso', 'Egreso'), ('Ingreso', 'Ingreso')], max_length=20)),
                ('fech_func', models.CharField(max_length=20)),
                ('const_1402', models.BooleanField()),
                ('const_1403', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_vaca', models.IntegerField(blank=True, null=True)),
                ('fech_inic', models.DateField(blank=True, max_length=50, null=True)),
                ('fech_culm', models.DateField(blank=True, max_length=50, null=True)),
                ('fech_rein', models.DateField(blank=True, max_length=50, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinacion', models.CharField(blank=True, max_length=255, null=True)),
                ('direc_linea', models.CharField(blank=True, max_length=255, null=True)),
                ('direc_gener', models.CharField(blank=True, max_length=255, null=True)),
                ('exten_tele', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_vaca', models.CharField(blank=True, choices=[('Reglamentarias', 'Reglamentarias'), ('Atrasadas', 'Atrasadas'), ('Adelantadas', 'Adelantadas')], max_length=50, null=True)),
                ('estatus', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=50, null=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constancias.Periodo')),
            ],
        ),
    ]
