# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-04 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabaexpe', '0001_initial'),
        ('constancias', '0004_cambio_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Procesando', 'Procesando'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=50, null=True)),
                ('fecha_s', models.DateTimeField(auto_now_add=True)),
                ('cod_jubila', models.IntegerField(blank=True, null=True)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trabaexpe.Expedientes')),
            ],
        ),
        migrations.RemoveField(
            model_name='segu_social',
            name='trami_pens',
        ),
    ]
