# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-05 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0005_auto_20190604_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pension',
            old_name='cod_jubila',
            new_name='cod_pen',
        ),
    ]
