# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-05 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0006_auto_20190604_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jubilacion',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabaexpe.Expedientes'),
        ),
        migrations.AlterField(
            model_name='pension',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabaexpe.Expedientes'),
        ),
    ]
