# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-05 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0008_auto_20190604_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='segu_social',
            name='observacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segu_social',
            name='esta_seg_soc',
            field=models.CharField(choices=[('Egreso', 'Egreso'), ('Ingreso', 'Ingreso'), ('Reingreso', 'Reingreso')], max_length=20),
        ),
    ]
