# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-05 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0009_auto_20190604_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segu_social',
            name='esta_seg_soc',
            field=models.CharField(choices=[('Egreso', 'Egreso'), ('Ingreso', 'Ingreso'), ('Reingreso', 'Reingreso')], default='Ingreso', max_length=20),
        ),
        migrations.AlterField(
            model_name='segu_social',
            name='fech_func',
            field=models.DateField(),
        ),
    ]
