# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-05 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0010_auto_20190605_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segu_social',
            name='fech_func',
            field=models.DateField(blank=True, null=True),
        ),
    ]
