# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2014-08-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import seguridad.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_auto_20190524_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=30, unique=True, verbose_name='Email')),
                ('cedula', models.CharField(max_length=30, unique=True, verbose_name='Cedula')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Apellido')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Administrador')),
                ('is_archivista', models.BooleanField(default=False, verbose_name='Arc')),
                ('is_analista_jubilacion', models.BooleanField(default=False, verbose_name='Jub')),
                ('is_analista_social', models.BooleanField(default=False, verbose_name='Seg')),
                ('is_analista_vacaciones', models.BooleanField(default=False, verbose_name='Vac')),
                ('is_trabajador', models.BooleanField(default=False, verbose_name='Trab')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            managers=[
                ('objects', seguridad.models.UserManager()),
            ],
        ),
    ]
