# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-05 21:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=800)),
                ('url', models.IntegerField()),
                ('tipo', models.CharField(choices=[('trabajador', 'trabajador'), ('vacaciones', 'vacaciones'), ('jubilacion', 'jubilacion'), ('seguro', 'seguro')], max_length=100)),
                ('estatus', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
