# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-05 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
